"""create army_units table

Revision ID: 2095651d64d8
Revises: 774c93dbad39
Create Date: 2026-05-01 00:56:50.357131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '2095651d64d8'
down_revision: Union[str, Sequence[str], None] = '774c93dbad39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('army_units',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('army_branch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['army_branch_id'], ['army_branches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_army_units_army_branch_id'), 'army_units', ['army_branch_id'], unique=False)
    op.create_index(op.f('ix_army_units_name'), 'army_units', ['name'], unique=False)
    op.create_index(op.f('ix_army_units_slug'), 'army_units', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_army_units_slug'), table_name='army_units')
    op.drop_index(op.f('ix_army_units_name'), table_name='army_units')
    op.drop_index(op.f('ix_army_units_army_branch_id'), table_name='army_units')
    op.drop_table('army_units')
    # ### end Alembic commands ###
