"""create vacancies table

Revision ID: 39713acc8dbb
Revises: 2095651d64d8
Create Date: 2026-05-04 14:05:18.205301

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = "39713acc8dbb"
down_revision: Union[str, Sequence[str], None] = "2095651d64d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vacancies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("responsibilities", sa.TEXT(), nullable=True),
        sa.Column("requirements", sa.TEXT(), nullable=True),
        sa.Column("conditions", sa.TEXT(), nullable=True),
        sa.Column(
            "service_type",
            sa.Enum("COMBAT", "REAR", name="vacancyservicetype"),
            nullable=False,
        ),
        sa.Column("army_unit_id", sa.Integer(), nullable=False),
        sa.Column("rank_group_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["army_unit_id"], ["army_units.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["rank_group_id"], ["rank_groups.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vacancies_name"), "vacancies", ["name"], unique=False)
    op.create_index(
        op.f("ix_vacancies_army_unit_id"), "vacancies", ["army_unit_id"], unique=False
    )
    op.create_index(
        op.f("ix_vacancies_rank_group_id"), "vacancies", ["rank_group_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vacancies_rank_group_id"), table_name="vacancies")
    op.drop_index(op.f("ix_vacancies_name"), table_name="vacancies")
    op.drop_index(op.f("ix_vacancies_army_unit_id"), table_name="vacancies")
    op.drop_table("vacancies")
    # ### end Alembic commands ###
